{% set name = "dadaist2" %}
{% set version = "0.7.6" %}
{% set sha256 = "df730e34a2c668fd0db10892047e55976690e5e1960707fc30077a2e459c0c8c" %}
{% set user = "quadram-institute-bioscience" %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  url: 'https://github.com/{{ user }}/{{ name }}/archive/v{{ version }}.tar.gz'
  sha256: '{{ sha256 }}'

build:
  number: 0
  noarch: generic

requirements:
  run:
    - perl
    - perl-fastx-reader >=0.90
    - python >=3
    - pandas >=1.0
    - biom-format
    - cutadapt
    - bioconductor-dada2
    - fastp
    - clustalo 
    - fasttree
    - bioconductor-phyloseq
    - bioconductor-microbiome
    - bioconductor-decipher
    - seqfu
    - qax
    
test:
  commands:
    - dadaist2 --version 2>&1 | grep -F '{{ version }}'


about:
  home: 'https://github.com/{{ user }}/{{ name }}'
  license: MIT
  summary: Command line wrapper to run DADA2 on a set of paired-end reads
  description: Command line wrapper to run DADA2 on a set of paired-end reads with several exporting tools to generate plots and numerical ecology analyses



